package Net::Async::Trello::CardAction;

use strict;
use warnings;

use parent qw(Net::Async::Trello::Generated::CardAction);

=head1 NAME

Net::Async::Trello::CardAction

=head1 DESCRIPTION

Autogenerated module.

=cut

1;

