package Net::Async::Trello::List;

use strict;
use warnings;

use parent qw(Net::Async::Trello::Generated::List);

=head1 NAME

Net::Async::Trello::List

=head1 DESCRIPTION

Autogenerated module.

=cut

sub subscribe {
	my ($self, %args) = @_;
    my $trello = $self->trello;
    my $list_id = $self->id;
    $trello->websocket->subscribe(
        type => 'list',
        id => $list_id
    )
}

sub cards {
	my ($self, %args) = @_;
    $self->trello->api_get_list(
		uri => 'lists/' . $self->id . '/cards', # ?fields=id,name,pos,idList,idShort,dateLastActivity',
        class => 'Net::Async::Trello::Card',
        extra => {
            list  => $self,
        },
    )
}


sub pos { shift->{pos} }
1;

