package Net::Async::Trello::List;

use strict;
use warnings;

use parent qw(Net::Async::Trello::Generated::List);

=head1 NAME

Net::Async::Trello::List

=head1 DESCRIPTION

Autogenerated module.

=cut

1;

