package Net::Async::Trello::List;

use strict;
use warnings;

=head1 NAME

Net::Async::Trello::List

=head1 DESCRIPTION

Autogenerated module.

=cut

use URI ();

=head1 METHODS

=cut

=head2 new

Instantiates.

=cut

sub new { my $class = shift; bless { @_ }, $class }

=head2 url

Provides an accessor for C<url>.

=cut

sub url { shift->{url} }

=head2 closed

Provides an accessor for C<closed>.

=cut

sub closed { shift->{closed} }

=head2 id_board

Provides an accessor for C<idBoard>.

=cut

sub id_board { shift->{idBoard} }

=head2 name

Provides an accessor for C<name>.

=cut

sub name { shift->{name} }

=head2 pos

Provides an accessor for C<pos>.

=cut

sub pos { shift->{pos} }

=head2 subscribed

Provides an accessor for C<subscribed>.

=cut

sub subscribed { shift->{subscribed} }

1;

