package Net::Async::Trello::Organisation;

use strict;
use warnings;

use parent qw(Net::Async::Trello::Generated::Organisation);

=head1 NAME

Net::Async::Trello::Organisation

=head1 DESCRIPTION

Autogenerated module.

=cut

1;

